DROP TABLE IF EXISTS trail;
CREATE TABLE trail (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    city VARCHAR(50),
    state VARCHAR(2),
    length FLOAT,
    difficulty INTEGER
);

INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Chubb Trail','Eureka','MO',6.7,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Lime Kiln Loop Trail','Wildwood','MO',2.8,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('DeClue Trail','Eureka','MO',8.4,5);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Salt Lick Trail','Valmeyer','IL',1.9,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Grotpeter Trail','Valley Park','MO',3.7,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Meramec River Greenway: Simpson Park to Arnold''s Grove','Valley Park','MO',3.5,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Bootleggers Run','Maryland Heights','MO',4.2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Green Rock Trail','Pacific','MO',14.7,5);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Historic Loop Trail','Pine Lawn','MO',1.3,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Katy Trail','Clinton','MO',248.4,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Deer Run Trail','Wildwood','MO',3,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Riverscene Trail','Valley Park','MO',3.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Out n Back','Maryland Heights','MO',1,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('North Prairie Loop','Eureka','MO',0.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Creve Coeur Connector','Saint Charles','MO',3.9,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Rock Hollow Trail','Eureka','MO',2.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('River Bluff Trail','Oakville','MO',0.9,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Barathaven Lake Trail Loop','Dardenne Prairie','MO',1.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Grant''s Trail','Oakland','MO',8.4,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Boschert Greenway Trail','Saint Charles','MO',5.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('River des Peres Greenway Trail','Shrewsbury','MO',5,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dardenne Greenway: Rabbit Run Park to Dardenne Park','Saint Peters','MO',2.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Deer Creek Greenway','Maplewood','MO',0.6,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Cottleville Trail','Cottleville','MO',1.2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Fox Run Trail','Town and Country','MO',0.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Centennial Greenway: Katy to Heritage','Saint Charles','MO',2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Sunset Greenway','Florissant','MO',3.9,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Connector 2','Valley Park','MO',1.2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('St. Stanislaus Truman Park Connector Trail','Hazelwood','MO',3.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('South Prairie Loop','Eureka','MO',0.8,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Spanish Trace Trail','Spanish Lake','MO',2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Nature Trail','Oakville','MO',1.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('St. Vincent Greenway','Cool Valley','MO',3.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Portage Des Sioux Nature Area Trail','Florissant','MO',1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Chinkapin Trail','Eureka','MO',0.4,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Maline Creek Trail','Bellefontaine Neighbors','MO',0.4,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Chipmunk Trail','Manchester','MO',0.6,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('George Winter Trail','Fenton','MO',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Oak Trail','Town and Country','MO',0.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('McKinley Bridge Bikeway and Branch Street Trestle','Venice','IL',1.2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Maple Tree Trail','Bellefontaine Neighbors','MO',1.4,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Fleurdelis Trail','Florissant','MO',0.7,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Confluence Point Trail','Hartford','IL',0.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hickory Hollow Trail','Green Park','MO',0.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Barathaven Lake Trail Spur 2','Dardenne Prairie','MO',1.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dogwood Trail','Town and Country','MO',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Cardinal Trail','Bellefontaine Neighbors','MO',1.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hawk''s Rest Trail','Green Park','MO',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Deer Path Trail','Green Park','MO',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Oak Knoll Parking Connector Trail','Clayton','MO',0.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Barathaven Lake Trail Connector','Dardenne Prairie','MO',0.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Barathaven Lake Trail Spur','Dardenne Prairie','MO',0.7,1);

INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Shaw Park Connector','Clayton','MO',0.2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Turkey Ridge Trail','Wildwood','MO',1.9,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Clark Trail','Weldon Spring','MO',5.1,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Flint Quarry Trail','Eureka','MO',1.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Mallard Lake Loop Trail','Maryland Heights','MO',2.7,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Al Foster Trail','Valley Park','MO',5.1,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Paw Paw Trail','Arnold','MO',0.4,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Crow''s Roost Trail','Arnold','MO',0.7,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Rock Quarry Trail','Wildwood','MO',1.7,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Fort Bella Fontaine Trail','Spanish Lake','MO',2.8,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Mississippi River Trail','Oakville','MO',4.7,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Busch Greenway','Weldon Spring','MO',4.8,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Meramec River Greenway: Fenton','Valley Park','MO',5.3,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Meramec Greenway Trail','Arnold','MO',2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Bealuh Loop Trail','Wildwood','MO',2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Lakeview Loop Trail','Maryland Heights','MO',3.9,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Country Crossing Trail','Cottleville','MO',0.6,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Bottomland Trail','Lakeshire','MO',0.6,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Chubb Trail Low Water Route','Eureka','MO',0.8,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Bison Trail','Valley Park','MO',3.3,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Cedar Bluff Trail','Valley Park','MO',2.5,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Eagle Valley Trail','Wildwood','MO',3.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Mississippi River Greenway: Jefferson Barracks Section','Lemay','MO',1.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Trail Among the Trees','Wildwood','MO',1.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Lost Valley Trail - Long Loop','Weldon Spring','MO',10.8,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Sandstone Canyon Trail','Cedar Hill','MO',3.7,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Limestone Hill Trail','Imperial','MO',2,5);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dogwood Trail','Eureka','MO',2.5,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Fishermen''s Trail','Arnold','MO',0.8,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Engelmann Woods Hiking Trail','Gray Summit','MO',1.5,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('METRO Corridor: Olive to Shaw Park','Olivette','MO',2.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hiking Trail','Byrnes Mill','MO',2.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('McDonnell Trail','Maryland Heights','MO',1.4,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Governor Bates Trail','Chesterfield','MO',1.1,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Central Park Trail','Chesterfield','MO',1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dennis Schick Trail N.','Lemay','MO',1.6,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Monarch Chesterfield Levee Trail','Chesterfield','MO',11.6,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hamilton Carr Trail','Wildwood','MO',1.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Mustang Trail','Wildwood','MO',1.7,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dennis Schick Trail S.','Lemay','MO',1.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Blue Heron Trail','Valley Park','MO',0.8,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Fox Run Fitness Trail','Green Park','MO',0.9,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Owl Creek Trail','Town and Country','MO',1,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Oak Knoll Trail','Richmond Heights','MO',0.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Riverwoods Trail','Saint Charles','MO',1.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Lakeside Trail','Spanish Lake','MO',1.4,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('River des Peres Greenway: St. Marcus Park','Lemay','MO',1.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Meramec Highland Quarry Trail','Des Peres','MO',0.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('LaBarque Hiking Trail','Pacific','MO',2.7,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Fern Hollow Trail','Winfield','MO',2.8,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Cannon Trail','Moscow Mills','MO',5.8,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Goddard River Trail','Gray Summit','MO',2.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Boone''s Crossing Trail','Weldon Spring','MO',1.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hickory Ridge Loop Trail','Sunset Hills','MO',1.2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Round House Loop Trail','Pacific','MO',2.7,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Wetland Trail','Gray Summit','MO',0.9,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Tanglevine Trail','Sunset Hills','MO',0.4,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Prairie Trail','Gray Summit','MO',0.8,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Towne Trail','Moscow Mills','MO',1.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Disabled Accessible Loop','Sunset Hills','MO',0.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Pool 4','Bridgeton','MO',1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Fox Creek Spur','Pacific','MO',0.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hawk Ridge Trail','Town and Country','MO',4.2,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Mississippi River Greenway: North Riverfront Trail','St. Louis','MO',14,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Lone Wolf Trail','Ballwin','MO',1.7,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Spring Valley Trail','Oakville','MO',2.1,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Bluffview Trail','Eureka','MO',2.2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Tall Timbers Trail','Arnold','MO',1.2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('LaBarque Hills Trail','Cedar Hill','MO',2.2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Columbia Bottom Trail','Spanish Lake','MO',7.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Cuivre River Trail South Loop','Troy','MO',7.5,5);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Meadows Loop Trail','Maryland Heights','MO',2.9,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Ruth Woods Trail','Olivette','MO',0.7,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Taconic Loop Trail','Byrnes Mill','MO',1.8,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('LeBarque Hills Trail','Byrnes Mill','MO',3.3,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Meramec Trail','Valley Park','MO',1.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Spring Valley Inner Loop','Oakville','MO',1.2,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Schwede Loop','Lake Saint Louis','MO',1.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Spice Bush Trail','Gray Summit','MO',1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('River Link','Saint Charles','MO',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Bluff Creek Trail','Sunset Hills','MO',1,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Kurtz Loop','Saint Charles','MO',0.9,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Goat Cliff Trail','Winfield','MO',1.3,5);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Slough Loop','Saint Charles','MO',1.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Main Trail','Chesterfield','MO',0.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('North Loop','O''Fallon','MO',0.4,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('South Loop','O''Fallon','MO',0.6,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Newman Trail','Valmeyer','IL',1.7,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Stemler Cave Woods Nature Preserve Trail','Millstadt','IL',2.1,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dogwood Trail','Wildwood','MO',1.8,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Woodbine Trail','Wildwood','MO',1.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Pine Trail','Weldon Spring','MO',0.2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Castlewood Loop Trail','Valley Park','MO',2.8,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Memorial Park','Brentwood','MO',0.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hogsback Trail','Gray Summit','MO',1.4,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Spring Branch Trail','Imperial','MO',0.8,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Shaw Park Loop','Clayton','MO',0.6,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hawthorn Trail','Wildwood','MO',1.1,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Virginia Day Memorial Nature Trail','Wildwood','MO',1.4,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Overlook Trail','Wildwood','MO',0.9,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Bicentennial Park Walking Trail','Belleville','IL',0.7,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Fossil Ridge Trail','Wildwood','MO',1.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Frenchmans Bluff Trail','Troy','MO',1.4,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hayes Trail','Gray Summit','MO',1.8,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Earth City Levee Trail','Saint Charles','MO',3.2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Broken Ridge Trail','Sunset Hills','MO',0.7,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Three Springs Park','Shiloh','IL',1.6,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Hickory Trail','Valley Park','MO',0.2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Shaw Park Trail','Clayton','MO',0.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Bike Trail','Wildwood','MO',1.9,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Podhorn Memorial Trail','Cottleville','MO',0.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Centennial Park','Swansea','IL',1,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Tunnel Trail','Valley Park','MO',0.1,5);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Open Play Trail','Chesterfield','MO',0.4,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Big Creek Trail','Moscow Mills','MO',0.8,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Equestrian Trail Access Spur 2','Wildwood','MO',1.1,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dog Park Trail','Chesterfield','MO',0.4,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Connector 3','Valley Park','MO',0.4,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Connector 4','Winchester','MO',0.4,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Connector 5','Valley Park','MO',0.2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Sunset Greenway Spur Trail','Hazelwood','MO',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Taconic Parking Loop','Byrnes Mill','MO',0.4,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Connector 1','Wildwood','MO',1,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('River des Peres Greenway: St. Marcus Park Spur','Lemay','MO',0.2,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Access Spur 1','Wildwood','MO',0.2,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Sandy Link','New Harmony','IN',0.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Taconic Loop Alternate','Byrnes Mill','MO',0.1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Beulah Trail','Wildwood','MO',4.3,4);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Equestrian Trail','Wildwood','MO',6.8,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Vantage Park Trail','Cottleville','MO',0.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Stinging Nettle Loop','Valley Park','MO',2.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Connector 9','Ellisville','MO',0.3,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Lake St. Albans Walking Path','Wildwood','MO',0.8,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Cattle Ridge Trail','Lake Saint Louis','MO',1.3,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dogwood Trail','Brentwood','MO',1,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Maple Trail','Brentwood','MO',0.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Woodland Trail','Lake Saint Louis','MO',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Howell Island Trail','Weldon Spring','MO',6.6,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Lakeside Park Trail','Saint Peters','MO',6.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Glen Travis Trail','Saint Peters','MO',0.5,2);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dardenne Greenway Spur Trail','Saint Peters','MO',0.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Ridge Trail','Winfield','MO',0.2,5);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Dogwood Trail','Winfield','MO',0.5,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('White Connector 1','Ballwin','MO',0.6,3);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('West Loop','Weldon Spring','MO',0.5,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Pool 3','Bridgeton','MO',1.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('South Loop','Weldon Spring','MO',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Three Springs Return','Shiloh','IL',0.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Pool 2','Bridgeton','MO',1.7,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Pool 1','Bridgeton','MO',2.3,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Pool 9','Bridgeton','MO',0.8,1);
INSERT INTO trail(name,city,state,length,difficulty) VALUES ('Ruth Woods Trail - Full Loop','Olivette','MO',0.9,2);